Update workflow for replacing secret api key

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -34,6 +34,19 @@ jobs:
           echo "SPRING_DATASOURCE_USERNAME=${{ secrets.SPRING_DATASOURCE_USERNAME }}" >> $GITHUB_ENV
           echo "SPRING_DATASOURCE_PASSWORD=${{ secrets.SPRING_DATASOURCE_PASSWORD }}" >> $GITHUB_ENV
 
+      - name: Replace API Key in environment.prod.ts and test
+        run: |
+          sed -i "s/REPLACE_THIS_WITH_API_KEY/${{ secrets.OPENWEATHER_KEY }}/g" ./frontend/src/environments/environment.prod.ts
+          if grep -q "REPLACE_THIS_WITH_API_KEY" ./frontend/src/environments/environment.prod.ts; then
+            echo "Replacement failed."
+            exit 1
+          else
+            echo "Replacement successful."
+          fi
+          
+          
+      
+
       - name: Build and test with Maven
         run: mvn clean install -Pprod  # Specify the Maven profile here
 
diff --git a/.github/workflows/main_pocasko.yml b/.github/workflows/main_pocasko.yml
--- a/.github/workflows/main_pocasko.yml
+++ b/.github/workflows/main_pocasko.yml
@@ -5,9 +5,6 @@
 name: Build and deploy JAR app to Azure Web App - Pocasko
 
 on:
-  push:
-    branches:
-      - main
   pull_request:
     branches:
       - main
@@ -18,54 +15,67 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      - uses: actions/checkout@v4
 
-      - name: Set up Java version
-        uses: actions/setup-java@v1
+      - uses: actions/checkout@v3
+
+      - name: Set up JDK 17
+        uses: actions/setup-java@v3
         with:
           java-version: '17'
+          distribution: 'temurin'
+          cache: maven
 
       - name: Set Environment Variables
         run: |
           echo "SPRING_DATASOURCE_URL=${{ secrets.SPRING_DATASOURCE_URL }}" >> $GITHUB_ENV
           echo "SPRING_DATASOURCE_USERNAME=${{ secrets.SPRING_DATASOURCE_USERNAME }}" >> $GITHUB_ENV
           echo "SPRING_DATASOURCE_PASSWORD=${{ secrets.SPRING_DATASOURCE_PASSWORD }}" >> $GITHUB_ENV
+          
+      - name: Replace API Key in environment.prod.ts and test
+        run: |
+          sed -i "s/REPLACE_THIS_WITH_API_KEY/${{ secrets.OPENWEATHER_KEY }}/g" ./frontend/src/environments/environment.prod.ts
+          if grep -q "REPLACE_THIS_WITH_API_KEY" ./frontend/src/environments/environment.prod.ts; then
+            echo "Replacement failed."
+            exit 1
+          else
+            echo "Replacement successful."
+          fi
 
-      #- name : set up node.js
-      #  uses: actions/setup-node@v3
-      #  with:
-      #    node-version: '18.18.2'
-      #    npm-version: '10.5.2'
+      - name : set up node.js
+        uses: actions/setup-node@v3
+        with:
+          node-version: '18.18.2'
+          npm-version: '10.5.2'
 
-      #- name : Install Angular Cli
-      #  run : npm install -g @angular/cli@17.3.5
-        #working-directory: ./frontend
-#
-#      - name: install npm dependencies
-#        run: npm install
-#        working-directory: ./frontend
-#
-#      - name: Check versions
-#        run: |
-#          node --version
-#          npm --version
-#          ng v
-#        working-directory: ./frontend
-#
-#
-#      - name: Build Angular Project
-#        run: ng build --base-href "/"
-#        working-directory: ./frontend
-#
-#      - name: Copy angular build artifacts
-#        run: |
-#          mkdir -p ./src/main/resources/static
-#          cp -R ./frontend/dist/frontend/browser/* ./src/main/resources/static/
-#        shell : bash
-#
-#      - name: List files in the static directory
-#        run: ls -lah ./src/main/resources/static/
-#        shell: bash
+      - name : Install Angular Cli
+        run : npm install -g @angular/cli@17.3.5
+        working-directory: ./frontend
+
+      - name: install npm dependencies
+        run: npm install
+        working-directory: ./frontend
+
+      - name: Check versions
+        run: |
+          node --version
+          npm --version
+          ng v
+        working-directory: ./frontend
+
+
+      - name: Build Angular Project
+        run: ng build --base-href "/"
+        working-directory: ./frontend
+
+      - name: Copy angular build artifacts
+        run: |
+          mkdir -p ./src/main/resources/static
+          cp -R ./frontend/dist/frontend/browser/* ./src/main/resources/static/
+        shell : bash
+
+      - name: List files in the static directory
+        run: ls -lah ./src/main/resources/static/
+        shell: bash
 
       - name: Build and test with Maven
         run: mvn clean install -Pprod
